dictionaries:
  - fonts
  - lorem-ipsum
  - node
useGitignore: true
words:
  - bunx
  - consectetuer
  - hoverable
  - licence
  - monolisa
  - naiveui
  - nodenext
  - npmjs
  - preparser
  - sghuang
  - slidev
  - toupper
  - trivago
  - unocss
  - vueuc
